# Generated by Django 5.0.6 on 2024-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
